server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dakucom/social_system_configServer.git
  rabbitmq:
    host: 192.168.146.137
management:   # 暴露触发消息总线的地址
  endpoint:
    web:
      exposure:
        include: bus-refresh
